### ISSUE TITLE
scss 스타일 관련 이슈

### ISSUE THREAD

**Issue by kyoung-jnn** [YAPP-19th/Web-Team-1-Frontend#14]
* [x] _variable.scss에 font-weight 변수 추가 (800, 900)
* [x] _variable.scss에 line-height 변수 추가, 기존에 Text 컴포넌트에는 `1.5, 2` 2개 밖에 존재하지 않습니다.
* [x] _variable.scss에 box-shadow 변수 수정, 피그마에 있지만 아직 없는 값이 존재합니다.

**Comment by raejoonee** [comment]
제가 해당하는 변수들 만들어서 PR 열까요? 아니면 @kyoung-jnn 님이 하실 계획이신가요?

**Comment by kyoung-jnn** [comment]
#15 PR 하실때 같이 해도 괜찮을 것 같습니다 ㅎㅎ
편하신대로 해주세여. PR 열면 제가 거기다가 commit 해도 되고용

**Comment by raejoonee** [comment]
혹시 `line-height`에 1.5, 2 말고 어떤 값들이 더 필요한지 알 수 있나요? `box-shadow`도 현재 있는 변수 제외하고 어떤 그림자가 필요한건지.. 아니면 모든 그림자를 현재 변수로 둔 `box-shadow`로 통일하면 안 되나요?

**Comment by raejoonee** [comment]
`font-weight`의 경우에는, 저희가 사용 중인 구글 웹폰트에서 100, 300, 400, 500, 700, 900만 지원하고 있습니다. 800은 추가할 수 없을 것 같아요 😢 그래서 일단은 [이 링크](https://fonts.google.com/noto/specimen/Noto+Sans+KR?preview.text=noto%20sans&preview.text_type=custom)에서 제공하는 모든 weight에 대해 변수 추가했습니다.
