### ISSUE TITLE
scss 내부, background url 이슈

### ISSUE THREAD

**Issue by kyoung-jnn** [YAPP-19th/Web-Team-1-Frontend#15]
- [x] scss 내부에서 `background url` 이 적용되지 않아서 이미지를 불러오지 못 합니다.
storybook 에서는 작동하나 localhost 에서는 문제가 발생합니다.

**Comment by raejoonee** [comment]
Webpack 관련 문제인 것 같습니다.

**Comment by raejoonee** [comment]
해결했습니다. Webpack 5버전부터는 `url-loader` 사용을 지양해야 하네요. Asset Modules를 사용하도록 수정하여 해결했고, 로컬에서 정상적으로 구동하는 것을 확인했습니다. 속도도 더 빨라졌네요!

[참고링크](https://webpack.kr/guides/asset-modules/)

**Comment by raejoonee** [comment]
PR 열고 merge 되면 이슈 닫겠습니다.

**Comment by kyoung-jnn** [comment]
계속 해결해볼려고 `resolve url loader` 같은 loader 설치해봤는데..
결국 공식문서에 답이 있네요 😢
