### ISSUE TITLE
폰트 관련 이슈

### ISSUE THREAD

**Issue by raejoonee** [YAPP-19th/Web-Team-1-Frontend#19]
## Issue
현재 **Noto Sans 폰트가 설치되지 않은 윈도우 컴퓨터에서 구글 크롬을 통해 스토리를 확인하는 경우**, 모든 스토리가 윈도우 기본 폰트로 보이는 문제가 있습니다. (issue raised by @sohyeonn2)

## Expected Solution
웹 폰트가 정상적으로 로드되지 못했거나, 크롬에서 사용하는 타입으로 전환되지 못하고 있는 것 같습니다. 프로젝트 내부에 폰트를 설치하는 방법으로 해결할 수 있을 것 같은데 어떻게 생각하시나요? @kyoung-jnn @LeeJuhae

**Comment by kyoung-jnn** [comment]
어느 윈도우 컴퓨터에는 되서 정확히 뭐가 문제인지 모르겠네요..
강산님과 소현님 @sohyeonn2  해결 안되시면 어쩔 수 없이 다운받아서 써야 할 것 같습니다.
근데 내부에 폰트 이용하면 프로젝트 크기에 문제가 없을까요?

**Comment by kyoung-jnn** [comment]
다같이 만나서 진행할때 자세히 확인해봐야 할 것 같아여
저번에 강산님도 안되셨어요

**Comment by raejoonee** [comment]
지금 확인해봤는데 폰트 문제가 아니고 특정 컴퓨터에서 특정 `font-weight` 수치만 적용이 안되고 있네요.. 원인 찾는중 😢

**Comment by kyoung-jnn** [comment]
저번에 소현님 컴퓨터 개발자 도구로 `font-weight` 수동으로 조절은 됐었어요

**Comment by raejoonee** [comment]
@sohyeonn2 피셜) 그때도 안 됐대요 😢 사실 지금 개발자 도구 켜서 해보라고 했는데 안되네용 😭

**Comment by kyoung-jnn** [comment]
😱

**Comment by raejoonee** [comment]
현재 Windows, MacOS, Android, iPhone에서 정상 동작함을 확인하였으나 일부 환경에서는 폰트가 정상적으로 보이지 않아서 해결 방법 찾는 중
