### ISSUE TITLE
패키지 의존성 오류

### ISSUE THREAD

**Issue by kyoung-jnn** [YAPP-19th/Web-Team-1-Frontend#34]
현재 `package-lock` 파일이 저희끼리 동일하지 않고 서로 다른 파일로 존재합니다.
이번에 올린 **PR** #33 에는 현재 **develop** 브랜치에 있는 기존에 사용했던 `lock` 파일로 올렸습니다.

**Comment by raejoonee** [comment]
#33 merge 하고 해결합시당 😄

**Comment by raejoonee** [comment]
#36 에서 해결됨
